config/routes.rb
# rubocop:disable all
Rails.application.routes.draw do
  get 'login', to: 'client/sessions#new'
  post 'login', to: 'client/sessions#create'
  get 'logout', to: 'client/sessions#destroy'
  root 'client/home#index'

  # client側route(pathにclientは含めないこと)
  get 'calender', to: 'client/calenders#index'
  resources :events, controller: 'client/events'
  resources :artists, controller: 'client/artists'
  resources :collaborators, controller: 'client/collaborators'
  resource :eventer, controller: 'client/eventer'
  resources :offers, controller: 'client/offer'

  # admin側route
  namespace :admin do
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    get 'logout', to: 'sessions#destroy'

    root 'dashboard#index'
    get 'dashboard', to: 'dashboard#index'

    get 'events', to: 'events#index'
    get 'events/:id', to: 'events#show', as: 'event'

    get 'eventers', to: 'eventers#index'
    get 'eventers/:id', to: 'eventers#show', as: 'eventer'

    get 'offers', to: 'offers#index'

    get 'friends', to: 'friends#index'

    get 'artists', to: 'artists#index'
    get 'artists/:id', to: 'artists#show', as: 'artist'

    get 'collaborators', to: 'collaborators#index'
    get 'collaborators/:id', to: 'collaborators#show', as: 'collaborator'

    resources :administrators

    get 'password', to: 'password#edit'
    patch 'password', to: 'password#update'
  end
end

app/models/administrator.rb
# == Schema Information
#
# Table name: administrators
#
#  id              :bigint(8)        not null, primary key
#  name            :string
#  password_digest :string           not null
#  role            :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Administrator < ApplicationRecord
  extend Enumerize
  has_secure_password

  validates :name, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 8 }
  enumerize :role, in: %w(root admin operator), scope: true, default: 'operator', predicates: true

  # 権限毎に操作を変える時に使う
  LEVEL = {
    'root' => 3,
    'admin' => 2,
    'operator' => 1
  }.freeze
end

app/controllers/admin/administrators_controller.rb
class Admin::AdministratorsController < Admin::ApplicationController
  before_action :authorize!
  protect_from_forgery with: :null_session

  def index
    @q = Administrator.ransack(params[:q])
    @administrators = @q.result(distinct: true).order(created_at: :desc).page(params[:page])
    pagination_count(Administrator)
  end

  def new
    @administrator = Administrator.new
  end

  def create
    @administrator = Administrator.new(admin_params)
    return render :new unless @administrator.save
    redirect_to admin_administrators_path, notice: 'Administrator created successfully.'
  end

  def edit
    target_administrator
  end

  def update
    return render :edit unless target_administrator.update(admin_params)
    redirect_to admin_administrators_path, notice: 'Administrator updated successfully.'
  end

  def destroy
    message = if target_administrator.role == 'root'
                'root管理者は削除できません。'
              elsif target_administrator == current_user
                '自分自身の削除はできません。'
              else
                target_administrator.destroy ? 'Administrator deleted successfully.' : 'Administrator deleted unsuccessfully.'
              end
    redirect_to admin_administrators_path, notice: message
  end

  private

  def admin_params
    params.require(:administrator).permit(:name, :password, :password_confirmation, :role)
  end

  def target_administrator
    @administrator = Administrator.find(params[:id])
  end
end

app/helpers/admin/administrators_helper.rb
module Admin::AdministratorsHelper
end

app/views/admin/administrators/_form.html.slim
= form_with(model: [:admin, @administrator], local: true) do |form|
  - if @administrator.errors.any?
    #error_explanation
    .alert.alert-warning[role="alert"]
      - @administrator.errors.full_messages.each do |message|
        li.mb-0
          = message
  .field
    .form-group
      label 名前
      = form.text_field :name, id: :admin_name, class: "form-control"
    .form-group
      label Password
      = form.password_field :password, id: :admin_password, class: "form-control"
    .form-group
      label Password confirmation
      = form.password_field :password_confirmation, id: :admin_password_confirmation, class: "form-control"
    .form-group
      label 権限
      br
      = form.select :role, {"管理者" => 'admin', "閲覧者" => 'operator'}, id: :amdin_role, class: "form-control"
  .actions
    = form.submit class: "btn btn-outline-success"

app/views/admin/administrators/edit.html.slim
.my-3.my-md-5
  .container
    .page-header
      h1.page-title
        | Edit administrator
    .row
      .col-12
        .card
          .card-body
            = render 'form'

app/views/admin/administrators/index.html.slim
.my-3.my-md-5
  .container
    .page-header
      h1.page-title
        | Administrators
      = link_to 'New', new_admin_administrator_path, class: 'button btn btn-outline-danger', style: 'margin-left: 10px'
      form.form-inline.pl-md-auto.ml-md-auto
        = search_form_for @q, url: admin_administrators_path do |form|
          = form.search_field :name_cont, placeholder: "Name", class: 'form-control mr-sm-2'
          = form.submit 'Search', class: 'button btn btn-outline-info my-2 my-sm-0'
    .card-container
      - @administrators&.each do |admin|
        .col-md-4.col-xl-3
          .card
            .card-status.bg-purple
            .card-header
              h3.card-title
                = admin.name
              .card-options
                = link_to content_tag(:i, '', class: 'fe fe-edit'), edit_admin_administrator_path(admin), style: 'margin-right: 10px; color: #000000;'
                = link_to content_tag(:i, '', class: 'fa fa-trash'), admin_administrator_path(admin), method: :delete, style: 'margin-right: 10px; color: #000000;', data: {confirm: '削除してもよろしいですか?'}
                = admin.role
                a.card-options-collapse data-toggle="card-collapse" href="#"
                  i.fe.fe-chevron-up
            .card-footer
              = "作成: #{admin.created_at.strftime('%y/%m/%d')} / 更新: #{admin.updated_at.strftime('%y/%m/%d')}"
    .col-sm-12
      = "合計#{@total_records}件 現在 #{@current_page}頁目で#{@current_start}件目~#{@current_end}件目まで表示中"
      .pagination-position
        = paginate @administrators

app/views/admin/administrators/new.html.slim
.my-3.my-md-5
  .container
    .page-header
      h1.page-title
        | New administrator
    .row
      .col-12
        .card
          .card-body
            = render 'form'