config/routes.rb
# rubocop:disable all
Rails.application.routes.draw do
  get 'login', to: 'client/sessions#new'
  post 'login', to: 'client/sessions#create'
  get 'logout', to: 'client/sessions#destroy'
  root 'client/home#index'

  # client側route(pathにclientは含めないこと)
  get 'calender', to: 'client/calenders#index'
  resources :events, controller: 'client/events'
  resources :artists, controller: 'client/artists'
  resources :collaborators, controller: 'client/collaborators'
  resource :eventer, controller: 'client/eventer'
  resources :offers, controller: 'client/offer'

  # admin側route
  namespace :admin do
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    get 'logout', to: 'sessions#destroy'

    root 'dashboard#index'
    get 'dashboard', to: 'dashboard#index'

    get 'events', to: 'events#index'
    get 'events/:id', to: 'events#show', as: 'event'

    get 'eventers', to: 'eventers#index'
    get 'eventers/:id', to: 'eventers#show', as: 'eventer'

    get 'offers', to: 'offers#index'

    get 'friends', to: 'friends#index'

    get 'artists', to: 'artists#index'
    get 'artists/:id', to: 'artists#show', as: 'artist'

    get 'collaborators', to: 'collaborators#index'
    get 'collaborators/:id', to: 'collaborators#show', as: 'collaborator'

    resources :administrators

    get 'password', to: 'password#edit'
    patch 'password', to: 'password#update'
  end
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id         :bigint(8)        not null, primary key
#  title      :string
#  date       :date
#  open       :time
#  start      :time
#  adv        :integer
#  door       :integer
#  concept    :text
#  house      :string
#  images     :string
#  aasm_state :string
#  eventer_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Event < ApplicationRecord
  include AasmEvent
  mount_uploader :images, EventUploader # carrierwave設定の時にまとめてやる

  validates :title, presence: true
  validates :concept, length: { maximum: 240 }

  # Event.artists オファーしたバンド一覧, Event.artists.where(aasm_state: :ok) 決定バンド一覧
  has_many :offers
  has_many :artists, through: :offers

  # Event.eventer 主催者
  belongs_to :eventer

  # Event.collaborative_eventers 共同制作者一覧
  has_many :collaborators
  has_many :collaborative_eventers, through: :collaborators, source: :eventer

  def my_offer(artist)
    offers.find_by(artist: artist)
  end

  def my_offered_artists(eventer)
    artists.where(eventer: eventer)
  end

  # aasm_state_artists でofferの状態がaasm_stateのartists一覧を取得できる Event.ok_artists
  Offer.aasm.states.map(&:name).each do |state|
    define_method("#{state}_artists".to_sym) do
      offers.where(aasm_state: state).map(&:artist)
    end
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::ApplicationController
  def index
    @q = Event.ransack(params[:q])
    @events = @q.result(distinct: true).order(created_at: :desc).page(params[:page])
    pagination_count(Event)
  end

  def show
    @event = Event.find(params[:id])
    @artists = {}
    @artists[:ok] = @event.ok_artists
    @artists[:ng] = @event.ng_artists
    @artists[:offering] = @event.offering_artists
    @artists[:candidate] = @event.candidate_artists
    @collaborators = @event.collaborative_eventers
  end
end

app/controllers/client/events_controller.rb
class Client::EventsController < Client::ArtistsController
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/client/events_helper.rb
module Client::EventsHelper
end

app/views/admin/events/index.html.slim
.my-3.my-md-5
  .container
    .page-header
      h1.page-title
        | Events
      form.form-inline.pl-md-auto.ml-md-auto
        = search_form_for @q, url: admin_events_path do |form|
          = form.search_field :title_cont, placeholder: "Title", class: 'form-control mr-sm-2'
          = form.submit 'Search', class: 'button btn btn-outline-info my-2 my-sm-0 '
    .card-container
      - @events&.each do |event|
        .col-md-4.col-xl-3
          .card
            .card-status.bg-green
            .card-header
              = image_tag(event.images.url , class: 'avatar')
              h3.card-title.avatar-side-content
                = link_to event.title, admin_event_path(event)
              .card-options
                = event.aasm_state
                a.card-options-collapse data-toggle="card-collapse" href="#"
                  i.fe.fe-chevron-up

            .card-body
              = "場所: #{event.house.present? ? event.house : '未設定'} "
              br
              = "日程: #{event.date.present? ? event.date.strftime('%y/%m/%d') : '未設定'}"
              br
              = "op/st : #{event.open.present? ? event.open : "tba"}/#{event.start.present? ? event.start : "tba"}"
              br
              = "adv/door : #{event.adv.present? ? event.adv : "tba"}/#{event.door.present? ? event.door : "tba"}"
              br
              - event.concept.present?
                = "[コンセプト]<br>#{event.concept}"
                br
              br
                |[決定act]
              - if event.ok_artists.present?
                - event.ok_artists&.each do |artist|
                  = "- #{link_to artist.name, admin_artist_path(artist)}".html_safe
                  br
              - else
                = "なし"
            .card-footer
              = "created_at #{event.created_at.strftime('%Y/%m/%d')} <br>by #{link_to event.eventer.name,admin_event_path(event.eventer) }".html_safe
    .col-sm-12
      = "合計#{@total_records}件 現在 #{@current_page}頁目で#{@current_start}件目~#{@current_end}件目まで表示中"
      .pagination-position
        = paginate @events

app/views/admin/events/show.html.slim
.my-3.my-md-5
  .container
    .row
      .col-lg-3
        .card.card-profile
          .card-header.bg-green
          .card-body.text-center
            = image_tag @event.images.url, class: 'card-profile-img'
            h3.mb-3
              = @event.title
            p.mb-4
              = @event&.concept

            .text-left

              = "場所: #{@event.house.present? ? @event.house : '未設定'} "
              br
              = "日程: #{@event.date.present? ? @event.date.strftime('%y/%m/%d') : '未設定'}"
              br
              = "op/st : #{@event.open.present? ? @event.open : "tba"}/#{@event.start.present? ? event.start : "tba"}"
              br
              = "adv/door : #{@event.adv.present? ? @event.adv : "tba"}/#{@event.door.present? ? event.door : "tba"}"
              br
              |[決定act]
              br
              - if @event.ok_artists.present?
                - @event.ok_artists&.each do |artist|
                  = "- #{link_to artist.name, admin_artist_path(artist)}".html_safe
                  br
              - else
                = "なし"
          .card-footer
            = "created_at #{@event.created_at.strftime('%Y/%m/%d')} <br>主催: #{link_to @event.eventer.name, admin_eventer_path}".html_safe

        - @collaborators&.each do |eventer|
          .page-header
            .page-title 共催者一覧
          .card.card-collapsed
            .card-status.bg-red
            .card-header
              = image_tag(eventer.avatar.url , class: 'avatar')
              h3.card-title.avatar-side-content
                = link_to eventer.name, admin_eventer_path(eventer)
              .card-options
                = eventer.my_collaboration(@event).role
                a.card-options-collapse data-toggle="card-collapse" href="#"
                  i.fe.fe-chevron-up
            .card-body
              = eventer.profile
              .text-left
              | [オファー一覧]
              br
              - @event.my_offered_artists(eventer)&.each do |artist|
                = "- #{artist.name}:　#{@event.my_offer(artist).aasm_state}"
                br

            .card-footer
              = "created_at: #{eventer.my_collaboration(@event).created_at.strftime('%Y/%m/%d')}"

      .col-lg-9
        .page-header
          .page-title 決定
        .card-container
          - @artists[:ok]&.each do |artist|
            .col-md-4
              .card.card-collapsed
                .card-status.bg-blue
                .card-header
                  = image_tag(artist.artist_image.url , class: 'avatar')
                  h3.card-title.avatar-side-content
                    = link_to artist.name, admin_artist_path
                  .card-options
                    = artist.my_offer(@event).aasm_state
                    a.card-options-collapse data-toggle="card-collapse" href="#"
                      i.fe.fe-chevron-up

                .card-body
                  = "直近のライブ: 直近のライブを持ってくる実装"
                  br
                  = "オファー数: 計#{artist.offers.count || 0}回"
                  br
                  = "決定数: 計#{artist.ok_count.count || 0}回"
                .card-footer
                  = "created_at #{artist.my_offer(@event).created_at.strftime('%Y/%m/%d')}"

        .page-header
          .page-title オファー中
        .card-container
          - @artists[:offering]&.each do |artist|
            .col-md-4
              .card.card-collapsed
                .card-status.bg-blue
                .card-header
                  = image_tag(artist.artist_image.url , class: 'avatar')
                  h3.card-title.avatar-side-content
                    = link_to artist.name, admin_artist_path
                  .card-options
                    = artist.my_offer(@event).aasm_state
                    a.card-options-collapse data-toggle="card-collapse" href="#"
                      i.fe.fe-chevron-up

                .card-body
                  = "直近のライブ: 直近のライブを持ってくる実装"
                  br
                  = "オファー数: 計#{artist.offers.count || 0}回"
                  br
                  = "決定数: 計#{artist.ok_count.count || 0}回"
                .card-footer
                  = "created_at #{artist.my_offer(@event).created_at.strftime('%Y/%m/%d')}"
        .page-header
          .page-title 候補
        .card-container
          - @artists[:condidate]&.each do |artist|
            .col-md-4
              .card.card-collapsed
                .card-status.bg-blue
                .card-header
                  = image_tag(artist.artist_image.url , class: 'avatar')
                  h3.card-title.avatar-side-content
                    = link_to artist.name, admin_artist_path
                  .card-options
                    = artist.my_offer(@event).aasm_state
                    a.card-options-collapse data-toggle="card-collapse" href="#"
                      i.fe.fe-chevron-up

                .card-body
                  = "直近のライブ: 直近のライブを持ってくる実装"
                  br
                  = "オファー数: 計#{artist.offers.count || 0}回"
                  br
                  = "決定数: 計#{artist.ok_count.count || 0}回"
                .card-footer
                  = "created_at #{artist.my_offer(@event).created_at.strftime('%Y/%m/%d')}"

        .page-header
          .page-title NG
        .card-container
          - @artists[:ng]&.each do |artist|
            .col-md-4
              .card.card-collapsed
                .card-status.bg-blue
                .card-header
                  = image_tag(artist.artist_image.url , class: 'avatar')
                  h3.card-title.avatar-side-content
                    = link_to artist.name, admin_artist_path
                  .card-options
                    = artist.my_offer(@event).aasm_state
                    a.card-options-collapse data-toggle="card-collapse" href="#"
                      i.fe.fe-chevron-up

                .card-body
                  = "直近のライブ: 直近のライブを持ってくる実装"
                  br
                  = "オファー数: 計#{artist.offers.count || 0}回"
                  br
                  = "決定数: 計#{artist.ok_count.count || 0}回"
                .card-footer
                  = "created_at #{artist.my_offer(@event).created_at.strftime('%Y/%m/%d')}"