config/routes.rb
# rubocop:disable all
Rails.application.routes.draw do
  get 'login', to: 'client/sessions#new'
  post 'login', to: 'client/sessions#create'
  get 'logout', to: 'client/sessions#destroy'
  root 'client/home#index'

  # client側route(pathにclientは含めないこと)
  get 'calender', to: 'client/calenders#index'
  resources :events, controller: 'client/events'
  resources :artists, controller: 'client/artists'
  resources :collaborators, controller: 'client/collaborators'
  resource :eventer, controller: 'client/eventer'
  resources :offers, controller: 'client/offer'

  # admin側route
  namespace :admin do
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    get 'logout', to: 'sessions#destroy'

    root 'dashboard#index'
    get 'dashboard', to: 'dashboard#index'

    get 'events', to: 'events#index'
    get 'events/:id', to: 'events#show', as: 'event'

    get 'eventers', to: 'eventers#index'
    get 'eventers/:id', to: 'eventers#show', as: 'eventer'

    get 'offers', to: 'offers#index'

    get 'friends', to: 'friends#index'

    get 'artists', to: 'artists#index'
    get 'artists/:id', to: 'artists#show', as: 'artist'

    get 'collaborators', to: 'collaborators#index'
    get 'collaborators/:id', to: 'collaborators#show', as: 'collaborator'

    resources :administrators

    get 'password', to: 'password#edit'
    patch 'password', to: 'password#update'
  end
end

app/models/eventer.rb
# == Schema Information
#
# Table name: eventers
#
#  id              :bigint(8)        not null, primary key
#  name            :string
#  avatar          :string
#  twitter_url     :string
#  profile         :text
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Eventer < ApplicationRecord
  # snsのカラムをvalidationしようと思ってるけど、そもそも更新を紐づけたときだけにしたら必要ないお
  before_validation :valid_twitter_url
  mount_uploader :avatar, EventerUploader # carrierwave設定の時にまとめてやる
  has_secure_password
  validates :name, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 8 }
  validates :profile, presence: true, length: { maximum: 240 }

  # Eventer.eventsで主催イベント一覧
  has_many :events
  # Eventer.eventsで登録バンド一覧
  has_many :artists
  # Eventer.collaborative_eventsで共同制作者としてのイベント一覧
  has_many :collaborators
  has_many :collaborative_events, through: :collaborators, source: :event

  def valid_twitter_url
    return true unless twitter_url
  end

  Event.aasm.states.map(&:name).each do |state|
    define_method("#{state}_events_count".to_sym) do
      events.where(aasm_state: state).count
    end
  end

  Event.aasm.states.map(&:name).each do |state|
    define_method("#{state}_collaborative_events_count".to_sym) do
      collaborative_events.where(aasm_state: state).count
    end
  end

  def my_collaboration(event)
    collaborators.find_by(event: event)
  end
end

app/controllers/admin/eventers_controller.rb
class Admin::EventersController < Admin::ApplicationController
  def index
    @q = Eventer.ransack(params[:q])
    @eventers = @q.result(distinct: true).order(created_at: :desc).page(params[:page])
    pagination_count(Eventer)
  end

  def show
    @eventer = Eventer.find(params[:id])
    @collabo_events = @eventer.collaborators.map(&:event)
  end
end

app/controllers/client/eventer_controller.rb
class Client::EventerController < Client::ArtistsController
end

app/helpers/admin/eventers_helper.rb
module Admin::EventersHelper
end

app/helpers/client/eventer_helper.rb
module Client::EventerHelper
end

app/views/admin/eventers/index.html.slim
.my-3.my-md-5
  .container
    .page-header
      h1.page-title
        | Eventers
      form.form-inline.pl-md-auto.ml-md-auto
        = search_form_for @q, url: admin_eventers_path do |form|
          = form.search_field :name_cont, placeholder: "Name", class: 'form-control mr-sm-2'
          = form.submit 'Search', class: 'button btn btn-outline-info my-2 my-sm-0 '
    .card-container
      - @eventers&.each do |eventer|
        .col-md-4.col-xl-3
          .card
            .card-status.bg-red
            .card-header
              = image_tag(eventer.avatar.url , class: 'avatar')
              h3.card-title.avatar-side-content
                = link_to eventer.name, admin_eventer_path(eventer)
              .card-options
                - if eventer.twitter_url
                  a href="#{eventer.twitter_url}"
                    i.fa.fa-twitter
                a.card-options-collapse data-toggle="card-collapse" href="#"
                  i.fe.fe-chevron-up
            .card-body
              = eventer.profile
              br
              br
              = "アーティスト数: #{eventer.artists.count}"
              br
              = "主催数: #{eventer.events.count}(#{eventer.fixed_events_count + eventer.finished_events_count})"
              br
              = "コラボ数: #{eventer.collaborators.count}(#{eventer.fixed_collaborative_events_count + eventer.finished_collaborative_events_count})"

            .card-footer
              = "created_at: #{eventer.created_at.strftime('%Y/%m/%d')}"
    .col-sm-12
      = "合計#{@total_records}件 現在 #{@current_page}頁目で#{@current_start}件目~#{@current_end}件目まで表示中"
      .pagination-position
        = paginate @eventers

app/views/admin/eventers/show.html.slim
.my-3.my-md-5
  .container
    .row
      .col-lg-3
        .card.card-profile
          .card-header style='background-color: #dc3545'
          .card-body.text-center
            = image_tag @eventer.avatar.url, class: 'card-profile-img'
            h3.mb-3
              = @eventer.name
            p.mb-4
              = @eventer.profile
            - if @eventer.twitter_url
              a.btn.btn-outline-primary.btn-sm href="#{@eventer.twitter_url}"
                span.fa.fa-twitter Follow
            .text-left
              br
              = link_to "アーティスト一覧: ", admin_artists_path
              = "合計数 #{@eventer.artists.count}"
              br
              = link_to "主催イベント一覧: ", admin_events_path
              = "合計数 #{@eventer.events.count}(#{@eventer.fixed_events_count + @eventer.finished_events_count})"
              br
              = link_to "共催イベント一覧: ", admin_events_path
              = "合計数 #{@eventer.collaborative_events.count}(#{@eventer.fixed_collaborative_events_count + @eventer.finished_collaborative_events_count})"
              br
              = "オファー待ち数: #{@eventer.events.map{|e| e.offering_artists}.count + @eventer.collaborative_events.map{|e| e.offering_artists}.count}"

          .card-footer
            = "created_at: #{@eventer.created_at.strftime('%Y/%m/%d')} <br> updated_at#{@eventer.updated_at.strftime('%Y/%m/%d')}".html_safe

      .col-lg-9
        .page-header
          .page-title.mx-auto 共催イベント一覧
        .card-container
          - @collabo_events&.each do |event|
            .col-md-4
              .card.card-collapsed
                .card-status.bg-green
                .card-header
                  = image_tag(event.images.url , class: 'avatar')
                  h3.card-title.avatar-side-content
                    = event.title
                  .card-options
                    = event.aasm_state
                    a.card-options-collapse data-toggle="card-collapse" href="#"
                      i.fe.fe-chevron-up
                .card-body
                  = "場所: #{event.house.present? ? event.house : '未設定'} "
                  br
                  = "日程: #{event.date.present? ? event.date.strftime('%y/%m/%d') : '未設定'}"
                  br
                  = "op/st : #{event.open.present? ? event.open : "tba"}/#{event.start.present? ? event.start : "tba"}"
                  br
                  = "adv/door : #{event.adv.present? ? event.adv : "tba"}/#{event.door.present? ? event.door : "tba"}"
                  br
                  br
                  = "自分のオファーバンド一覧と状態が確認できるようにする"
                .card-footer
                  = "created_at #{event.created_at.strftime('%Y/%m/%d')} <br>by #{event.eventer.name}".html_safe