config/routes.rb
# rubocop:disable all
Rails.application.routes.draw do
  get 'login', to: 'client/sessions#new'
  post 'login', to: 'client/sessions#create'
  get 'logout', to: 'client/sessions#destroy'
  root 'client/home#index'

  # client側route(pathにclientは含めないこと)
  get 'calender', to: 'client/calenders#index'
  resources :events, controller: 'client/events'
  resources :artists, controller: 'client/artists'
  resources :collaborators, controller: 'client/collaborators'
  resource :eventer, controller: 'client/eventer'
  resources :offers, controller: 'client/offer'

  # admin側route
  namespace :admin do
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    get 'logout', to: 'sessions#destroy'

    root 'dashboard#index'
    get 'dashboard', to: 'dashboard#index'

    get 'events', to: 'events#index'
    get 'events/:id', to: 'events#show', as: 'event'

    get 'eventers', to: 'eventers#index'
    get 'eventers/:id', to: 'eventers#show', as: 'eventer'

    get 'offers', to: 'offers#index'

    get 'friends', to: 'friends#index'

    get 'artists', to: 'artists#index'
    get 'artists/:id', to: 'artists#show', as: 'artist'

    get 'collaborators', to: 'collaborators#index'
    get 'collaborators/:id', to: 'collaborators#show', as: 'collaborator'

    resources :administrators

    get 'password', to: 'password#edit'
    patch 'password', to: 'password#update'
  end
end

app/controllers/admin/password_controller.rb
class Admin::PasswordController < Admin::ApplicationController
  def edit; end

  def update
    if current_password?
      return redirect_to admin_root_path if @current_user.update(admin_params)
    end
    render :edit
  end

  private

  def current_password?
    !!current_user.authenticate(params[:current_password])
  end

  def admin_params
    params.require(:administrator).permit(:password, :password_confirmation)
  end
end

app/helpers/admin/password_helper.rb
module Admin::PasswordHelper
end

app/views/admin/password/_form.html.slim
= form_with(model: [:admin, @current_user],url: admin_password_path, local: true) do |form|
  - if @current_user.errors.any?
    #error_explanation
    .alert.alert-warning[role="alert"]
      - @current_user.errors.full_messages.each do |message|
        li.mb-0
          = message
  .field
    label Current password
    = password_field_tag :current_password, nil, placeholder: 'Enter current password', class: 'form-control'
    .form-group
      label Password
      = form.password_field :password, id: :admin_password, placeholder: 'Enter new password', class: "form-control"
    .form-group
      label Password confirmation
      = form.password_field :password_confirmation, id: :admin_password_confirmation, placeholder: 'Reenter new password', class: "form-control"
  .actions
    = form.submit class: "btn btn-outline-success"

app/views/admin/password/edit.html.slim
.my-3.my-md-5
  .container
    .page-header
      h1.page-title
        | Edit password
    .row
      .col-12
        .card
          .card-body
            = render 'form'